### ISSUE TITLE
ischyonte-000 validator stopped synchronizing on v0.7.1

### ISSUE THREAD

**Issue by fgimenez** [regen-network/testnets#259]
Running on v0.7.1, i noticed that my validator was jailed, checking the logs I found a lot of entries like this:
```
E[2020-03-24|00:51:32.887] Stopping peer for error                      module=p2p peer="Peer{MConn{173.249.40.87:26656} 4efed1cf14c69aee0695837fc7341036fe7dcc52 out}" err="pong timeout"
E[2020-03-24|00:51:44.125] Connection failed @ sendRoutine              module=p2p peer=ad044dbb96cfc65ee97810faa48a853a3906c9c6@172.104.145.220:26656 conn=MConn{172.104.145.220:26656} err="pong timeout"
E[2020-03-24|00:51:44.125] Stopping peer for error                      module=p2p peer="Peer{MConn{172.104.145.220:26656} ad044dbb96cfc65ee97810faa48a853a3906c9c6 out}" err="pong timeout"
E[2020-03-24|00:51:44.440] Connection failed @ sendRoutine              module=p2p peer=0d354fdae833c3e26d52ed02f9ed967682e79d1f@66.232.119.130:26656 conn=MConn{66.232.119.130:26656} err="pong timeout"
E[2020-03-24|00:51:44.440] Stopping peer for error                      module=p2p peer="Peer{MConn{66.232.119.130:26656} 0d354fdae833c3e26d52ed02f9ed967682e79d1f out}" err="pong timeout"
E[2020-03-24|00:52:14.156] Connection failed @ sendRoutine              module=p2p peer=86e4a20f8c7f3f8bc646f8f35db0e22d45079395@80.241.217.149:26656 conn=MConn{80.241.217.149:26656} err="pong timeout"
E[2020-03-24|00:52:14.157] Stopping peer for error                      module=p2p peer="Peer{MConn{80.241.217.149:26656} 86e4a20f8c7f3f8bc646f8f35db0e22d45079395 out}" err="pong timeout"
E[2020-03-24|00:52:44.137] Connection failed @ sendRoutine              module=p2p peer=96e61f52c6d1fd9de811b7e0858d634d6ed86452@51.145.151.205:26656 conn=MConn{51.145.151.205:26656} err="pong timeout"
E[2020-03-24|00:52:44.137] Stopping peer for error                      module=p2p peer="Peer{MConn{51.145.151.205:26656} 96e61f52c6d1fd9de811b7e0858d634d6ed86452 out}" err="pong timeout"
E[2020-03-24|00:53:08.103] Connection failed @ sendRoutine              module=p2p peer=8aea2394d2e9474dbe67cfcbeb67fb01421ca9d8@159.89.249.168:26656 conn=MConn{159.89.249.168:26656} err="pong timeout"
E[2020-03-24|00:53:08.103] Stopping peer for error                      module=p2p peer="Peer{MConn{159.89.249.168:26656} 8aea2394d2e9474dbe67cfcbeb67fb01421ca9d8 out}" err="pong timeout"
E[2020-03-24|00:53:14.124] Connection failed @ sendRoutine              module=p2p peer=4357200765f03645e746b85832f24d7a8502e31d@172.104.242.5:26656 conn=MConn{172.104.242.5:26656} err="pong timeout"
E[2020-03-24|00:53:14.125] Stopping peer for error                      module=p2p peer="Peer{MConn{172.104.242.5:26656} 4357200765f03645e746b85832f24d7a8502e31d out}" err="pong timeout"
E[2020-03-24|00:53:14.143] Connection failed @ sendRoutine              module=p2p peer=3f931256cb882756133fa0daebbffc86f6b26cfb@173.249.53.224:26656 conn=MConn{173.249.53.224:26656} err="pong timeout"
E[2020-03-24|00:53:14.144] Stopping peer for error                      module=p2p peer="Peer{MConn{173.249.53.224:26656} 3f931256cb882756133fa0daebbffc86f6b26cfb out}" err="pong timeout"
E[2020-03-24|00:53:17.939] Connection failed @ sendRoutine              module=p2p peer=4efed1cf14c69aee0695837fc7341036fe7dcc52@173.249.40.87:26656 conn=MConn{173.249.40.87:26656} err="pong timeout"
E[2020-03-24|00:53:17.940] Stopping peer for error                      module=p2p peer="Peer{MConn{173.249.40.87:26656} 4efed1cf14c69aee0695837fc7341036fe7dcc52 out}" err="pong timeout"
E[2020-03-24|00:53:44.973] Connection failed @ sendRoutine              module=p2p peer=7dad3011330030094b355e3a9d1667970f255f57@206.189.94.44:26656 conn=MConn{206.189.94.44:26656} err="pong timeout"
E[2020-03-24|00:53:44.973] Stopping peer for error                      module=p2p peer="Peer{MConn{206.189.94.44:26656} 7dad3011330030094b355e3a9d1667970f255f57 out}" err="pong timeout"
E[2020-03-24|00:53:59.117] dialing failed (attempts: 1): auth failure: conn.ID (ad044dbb96cfc65ee97810faa48a853a3906c9c6) dialed ID (e7c1c61d41abbc66fab0493f7921289751db1f62) mismatch module=pex addr=e7c1c61d41abbc66fab0493f7921289751db1f62@172.104.145.220:26656
E[2020-03-24|00:54:14.125] Connection failed @ sendRoutine              module=p2p peer=e39f9473e38713cfcb3ca232ce863713a9345187@172.105.93.229:26656 conn=MConn{172.105.93.229:26656} err="pong timeout"
E[2020-03-24|00:54:14.125] Stopping peer for error                      module=p2p peer="Peer{MConn{172.105.93.229:26656} e39f9473e38713cfcb3ca232ce863713a9345187 out}" err="pong timeout"
E[2020-03-24|00:54:14.154] Connection failed @ sendRoutine              module=p2p peer=d32432f9c5465aa0d1d9314051bf9a4d28e3bc08@164.68.101.56:26656 conn=MConn{164.68.101.56:26656} err="pong timeout"
E[2020-03-24|00:54:14.154] Stopping peer for error                      module=p2p peer="Peer{MConn{164.68.101.56:26656} d32432f9c5465aa0d1d9314051bf9a4d28e3bc08 out}" err="pong timeout"
E[2020-03-24|00:54:14.154] Connection failed @ sendRoutine              module=p2p peer=b838b89bc821b98d7ca3ce963c2e75fc4810b124@5.189.150.170:26656 conn=MConn{5.189.150.170:26656} err="pong timeout"
E[2020-03-24|00:54:14.154] Stopping peer for error                      module=p2p peer="Peer{MConn{5.189.150.170:26656} b838b89bc821b98d7ca3ce963c2e75fc4810b124 out}" err="pong timeout"
E[2020-03-24|00:54:53.125] Connection failed @ sendRoutine              module=p2p peer=8aea2394d2e9474dbe67cfcbeb67fb01421ca9d8@159.89.249.168:26656 conn=MConn{159.89.249.168:26656} err="pong timeout"
E[2020-03-24|00:54:53.125] Stopping peer for error                      module=p2p peer="Peer{MConn{159.89.249.168:26656} 8aea2394d2e9474dbe67cfcbeb67fb01421ca9d8 out}" err="pong timeout"
E[2020-03-24|00:54:59.113] dialing failed (attempts: 15): dial tcp 164.68.118.125:26656: connect: connection refused module=pex addr=b1ad84bf1e1531c57816dddcb0c9cd199eff1702@164.68.118.125:26656
```
On first restart I got these log:
```
I[2020-03-24|11:53:16.803] starting ABCI with Tendermint                module=main 
panic: Failed to process committed block (145162:135215864F2F0A6452BC3C4DC2F75F547664FEA79F139204FE3019D56B731B28): wrong Block.Header.AppHash.  Expected 4F0E1A7D3D239D6BA42466E1AC75BF76A12CA185FCC6C48ED9A133AD4BE7521F, got E9DE1CF669FF9A60BA7E41D9A6A0D2BADE467C5F988050CB271B0F3349B9783A

goroutine 969 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000cd76c0)
 github.com/tendermint/tendermint@v0.33.0/blockchain/v0/reactor.go:344 +0x12ff
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
 github.com/tendermint/tendermint@v0.33.0/blockchain/v0/reactor.go:118 +0x84
```
And on each subsequent restart:
```
I[2020-03-24|11:56:24.846] starting ABCI with Tendermint                module=main 
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 4F0E1A7D3D239D6BA42466E1AC75BF76A12CA185FCC6C48ED9A133AD4BE7521F, got E9DE1CF669FF9A60BA7E41D9A6A0D2BADE467C5F988050CB271B0F3349B9783A
```
In order to recover the validator i needed to issue an `unsafe-reset-all` and synchronize from scratch.

**Comment by anilcse** [comment]
You should use v0.7.2 right?

**Comment by fgimenez** [comment]
Yep, i was reporting what happened while on v0.7.1, feel free to close if it is no longer relevant.

**Comment by anilcse** [comment]
Yeah, closing this as it looks like an issue with operating wrong binary.

**Comment by fgimenez** [comment]
:+1: for the record this started happening suddenly, the validator was working fine and i noticed that it was jailed and saw all the error logs, all without changing the binary.
